CREATE TABLE IF NOT EXISTS `qb_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `parent_id` BIGINT NOT NULL DEFAULT 0,
  `name` VARCHAR(128) NOT NULL,
  `description` VARCHAR(500) DEFAULT NULL,
  `sort_no` INT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_qb_category_tenant_parent` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `qb_question` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  `title` TEXT NOT NULL,
  `type` VARCHAR(32) NOT NULL,
  `multi_select` TINYINT NOT NULL DEFAULT 0,
  `difficulty` VARCHAR(32) NOT NULL,
  `default_score` INT NOT NULL,
  `analysis` TEXT DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_qb_question_tenant_category` (`tenant_id`, `category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `qb_question_choice` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `question_id` BIGINT NOT NULL,
  `choice_key` VARCHAR(16) NOT NULL,
  `choice_text` TEXT NOT NULL,
  `correct` TINYINT NOT NULL DEFAULT 0,
  `sort_no` INT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_qb_choice_tenant_question` (`tenant_id`, `question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `qb_question_answer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `question_id` BIGINT NOT NULL,
  `answer_text` TEXT DEFAULT NULL,
  `grading_rule` TEXT DEFAULT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qb_answer_question` (`question_id`),
  KEY `idx_qb_answer_tenant_question` (`tenant_id`, `question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `assignment_paper` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `description` VARCHAR(1000) DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `total_score` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `question_count` INT NOT NULL DEFAULT 0,
  `duration` INT NOT NULL,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_assignment_paper_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `assignment_paper_question` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `paper_id` BIGINT NOT NULL,
  `question_id` BIGINT NOT NULL,
  `score` DECIMAL(10,2) NOT NULL,
  `sort_no` INT NOT NULL DEFAULT 0,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_assignment_pq_tenant_paper` (`tenant_id`, `paper_id`),
  KEY `idx_assignment_pq_tenant_question` (`tenant_id`, `question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `assignment_exam_publish` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `paper_id` BIGINT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` VARCHAR(1000) DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `pass_score` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `total_score` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `question_count` INT NOT NULL DEFAULT 0,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_assignment_exam_publish_tenant_status` (`tenant_id`, `status`),
  KEY `idx_assignment_exam_publish_tenant_paper` (`tenant_id`, `paper_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `assignment_exam_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `publish_id` BIGINT DEFAULT NULL,
  `publish_title` VARCHAR(200) DEFAULT NULL,
  `paper_id` BIGINT NOT NULL,
  `student_id` BIGINT DEFAULT NULL,
  `student_name` VARCHAR(100) NOT NULL,
  `score` DECIMAL(10,2) DEFAULT NULL,
  `objective_score` DECIMAL(10,2) DEFAULT NULL,
  `subjective_score` DECIMAL(10,2) DEFAULT NULL,
  `answers` LONGTEXT DEFAULT NULL,
  `start_time` DATETIME DEFAULT NULL,
  `end_time` DATETIME DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'IN_PROGRESS',
  `window_switches` INT NOT NULL DEFAULT 0,
  `grader_id` BIGINT DEFAULT NULL,
  `graded_time` DATETIME DEFAULT NULL,
  `review_comment` VARCHAR(1000) DEFAULT NULL,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_assignment_exam_record_tenant_paper` (`tenant_id`, `paper_id`),
  KEY `idx_assignment_exam_record_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `assignment_exam_answer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT NOT NULL,
  `exam_record_id` BIGINT NOT NULL,
  `question_id` BIGINT NOT NULL,
  `question_type` VARCHAR(32) NOT NULL,
  `question_title` TEXT NOT NULL,
  `standard_answer` TEXT DEFAULT NULL,
  `user_answer` TEXT DEFAULT NULL,
  `max_score` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `score` DECIMAL(10,2) DEFAULT NULL,
  `correct_flag` TINYINT DEFAULT NULL,
  `ai_comment` TEXT DEFAULT NULL,
  `teacher_comment` TEXT DEFAULT NULL,
  `reviewed` TINYINT NOT NULL DEFAULT 0,
  `create_by` BIGINT DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_assignment_exam_answer_tenant_record` (`tenant_id`, `exam_record_id`),
  KEY `idx_assignment_exam_answer_tenant_question` (`tenant_id`, `question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
