geocourse:
  tenant:
    default-tenant-id: 1001
  infrastructure:
    mysql:
      host: 8.154.18.171
      port: 3306
      database: geocourse
      username: root
      password: root123456
    redis:
      host: 8.154.18.171
      port: 26739
      password: redis123456
      database: 0
    minio:
      endpoint: http://8.154.18.171:19000
      console-endpoint: http://8.154.18.171:19001
      access-key: minio
      secret-key: minio123456
      bucket: geocourse
      public-url: http://8.154.18.171:19000/geocourse
