server:
  forward-headers-strategy: framework

spring:
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  data:
    redis:
      ssl:
        enabled: false

logging:
  level:
    com.bddk.geocourse: INFO

geocourse:
  tenant:
    default-tenant-id: ${TENANT_DEFAULT_ID:1001}
  infrastructure:
    mysql:
      host: ${MYSQL_HOST:127.0.0.1}
      port: ${MYSQL_PORT:3306}
      database: ${MYSQL_DATABASE:geocourse}
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:root123456}
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:26739}
      password: ${REDIS_PASSWORD:redis123456}
      database: ${REDIS_DATABASE:0}
    minio:
      endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:19000}
      console-endpoint: ${MINIO_CONSOLE_ENDPOINT:http://127.0.0.1:19001}
      access-key: ${MINIO_ACCESS_KEY:minio}
      secret-key: ${MINIO_SECRET_KEY:minio123456}
      bucket: ${MINIO_BUCKET:geocourse}
      public-url: ${MINIO_PUBLIC_URL:http://8.154.18.171:19000/geocourse}

